export const LOGIN_TITLE = 'Вход'
export const BUTTON_TEXT = 'Войти'
export const EMAIL_PLACEHOLDER = 'Электронная почта'
export const PASSWORD_PLACEHOLDER = 'Пароль'
export const QUESTION_TEXT = 'Вы еще не зарегистрированы ?'